version: '3.7'

services:

  mongo:
    image: mongo
    container_name: awesome_mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: awesome_db
      MONGO_INITDB_ROOT_USERNAME: awesome_user
      MONGO_INITDB_ROOT_PASSWORD: awesome_user_password
